server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://${sql_ip_address}:3306/dota2?characterEncoding=utf8&cacheServerConfiguration=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true
    username: ${sql_username}
    password: ${sql_password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ${sql_ip_address}
    port: 6379
#  jpa:
                   #    show-sql: true

steam:
  api:
    url:
      dota2:
        IEcon: http://api.steampowered.com/IEconDOTA2_570/
        IDOTA2: http://api.steampowered.com/IDOTA2Match_570/
      steam:
        user: http://api.steampowered.com/ISteamUser/
    version:
      v1: v1/?
    key:
      second: key=203567935DB339ED47B8D3941A471E1D
      third: key=513EF62DDF1E62889C0022E7C668EAD0
    and: "&"
    language:
      zh: language=zh

admin:
  steamId: 76561198088256001