server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://144.202.116.140:3306/dota2?characterEncoding=utf8&cacheServerConfiguration=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: 784533
    driver-class-name: com.mysql.jdbc.Driver

steam:
  api:
    url:
      dota2:
        IEcon: http://api.steampowered.com/IEconDOTA2_570/
        IDOTA2: http://api.steampowered.com/IDOTA2Match_570/
      steam:
        user: http://api.steampowered.com/ISteamUser/
    version:
      v1: v1/
    key: ?key=EFA1E81676FCC47157EA871A67741EF5
    and: "&"
    language:
      zh: language=zh

admin:
  steamId: 76561198088256001